language: go
go: 1.5
before_install:
  - sudo apt-get update
  - sudo apt-get install haskell-platform
script:
  - cabal update
  - cabal install --enable-tests --only-dependencies
  - cabal configure --enable-tests
  - cabal test
  - make dist
