language: go
go: 1.5

cache:
  directories:
    - .cabal-sandbox

env:
  global:
    - CABALVER=1.22
    - GHCVER=7.10.1
    - HAPPYVER=1.19.5
    - ALEXVER=3.1.4

before_install:
  - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
  - travis_retry sudo apt-get update
  - travis_retry sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER
  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
  - travis_retry sudo apt-get install alex-$ALEXVER
  - export PATH=/opt/alex/$ALEXVER/bin:$PATH
  - travis_retry sudo apt-get install happy-$HAPPYVER
  - export PATH=/opt/happy/$HAPPYVER/bin:$PATH
  - cabal update

script:
  - cabal sandbox init
  - cabal install --enable-tests --only-dependencies
  - cabal configure --enable-tests
  - cabal test
  - make dist
