language: go
go: 1.5
before_install:
  - sudo apt-get update
  - sudo apt-get install haskell-platform
script:
  - cabal install --enable-tests --only-dependencies && cabal configure --enable-tests
  - make test dist
